box: jakirkham/centos_drmaa_conda
build:
    steps:
        - script:
            name: Ensure clean repo.
            code: |-
                git update-index -q --refresh

        - script:
            name: Build Conda Package.
            code: |-
                conda config --add channels nanshe
                conda config --set show_channel_urls True
                source activate root
                conda update -y --all
                python setup.py bdist_conda

        - script:
            name: Create Conda Environment with package and dependencies.
            code: |-
                conda create -y --use-local -n testenv nomkl nanshe==$(python setup.py --version)
                conda update -y --use-local -n testenv --all
                conda install -y --use-local -n testenv nanshe==$(python setup.py --version)
                source activate testenv

        - script:
            name: Install development copy of scikit-learn.
            code: |-
                touch /var/lib/rpm/*
                yum install -y gcc gcc-c++
                conda install -y cython
                conda remove -y scikit-learn
                pip install git+https://github.com/jakirkham/scikit-learn.git@dict_pos_constrt#egg=scikit-learn

        - script:
            name: Install dependencies for cluster support.
            code: |-
                conda install -y drmaa

        - script:
            name: Install dependencies for building docs.
            code: |-
                echo "sphinx 1.3.*" >> /opt/conda/envs/testenv/conda-meta/pinned
                conda install -y sphinx
                conda install -y cloud_sptheme

        - script:
            name: Install dependencies for profiling and monitoring coverage.
            code: |-
                conda install -y nose-timer
                echo "coverage 3.*" >> /opt/conda/envs/testenv/conda-meta/pinned
                conda install -y coverage
                conda install -y docstring-coverage
                conda install -y python-coveralls

        - script:
            name: Clean the environment.
            code: |-
                conda clean -tipsy

        - script:
            name: Test code.
            code: |-
                python setup.py nosetests --with-timer

        - script:
            name: Test documentation.
            code: |-
                python setup.py build_sphinx
                docstring-coverage nanshe | tee .docstring-coverage

    after-steps:
        - email-notify:
            from: alerts@wercker.com
            to: $TO_EMAIL
            username: $FROM_EMAIL
            password: $PASS
            host: smtp.gmail.com:587
